services:
  todo-app-front:
    container_name: frontend
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000

  todo-app-back:
    container_name: backend
    build:
      context: .
      dockerfile: ./todo-backend/dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app

    ports:
      - 4500:4500

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-app-front
      - todo-app-back