POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pY2hhbGVqYWNrc29uQGV4YW1wbGUuY29tIiwiaWQiOjMsImlhdCI6MTY3Nzg1NDAxNH0.P2dLd3IFlBY7IGaV2by0UQpaG8jfnYkcHuJQbJrlKxc

{
    "url": "facebook.com",
    "author": "Makr zuckerbergers",
    "title": "Meta verse is the new big thing",
    "year": 1994
}

