POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ASDADASDASDAS",
    "name": "aghhh oohhh",
    "password": "gfdgksfdklg",
    "blogs":[
            {           
                "title": "a new blog tditle",
                "author": "a Veyr badasd author",
                "url": "google.csom",
                "like": 5,
                "id": 123452678
            }  
            ]
}