version: '3.8'

services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./:/usr/src/app
    ports:
      - 4500:4500
    depends_on:
      - mongo 
      - redis
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:       
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    ports:
      - 3456:27017

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    container_name: redis
    volumes:
      - ./redis_data:/data


#      - REDIS_URL=redis://redis:6379
#      - MONGO_URL=mongodb://the_username:the_password@mongo:27107/the_database